# Generated by Django 6.0.2 on 2026-03-12 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='purpose',
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_duration',
            field=models.PositiveIntegerField(default=60, help_text='Expected duration in minutes'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='office_location',
            field=models.CharField(blank=True, help_text='e.g., Block C - Room 205', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_category',
            field=models.CharField(choices=[('MEETING', 'Business Meeting'), ('INTERVIEW', 'Job Interview'), ('DELIVERY', 'Delivery/Pickup'), ('MAINTENANCE', 'Maintenance/Repair'), ('STUDENT_VISIT', 'Student Visit'), ('OFFICIAL', 'Official Business'), ('PERSONAL', 'Personal Visit'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_details',
            field=models.TextField(default='General visit', help_text='Specific purpose of visit'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Host Confirmation'), ('APPROVED', 'Approved by Host'), ('CHECKED_IN', 'Checked In'), ('IN_MEETING', 'Meeting in Progress'), ('COMPLETED', 'Visit Completed'), ('EXPIRED', 'Visit Expired'), ('DENIED', 'Denied by Host')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='guard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='VisitorConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_type', models.CharField(choices=[('EXPECTED', 'Host Confirmed Expecting Visitor'), ('ARRIVED', 'Host Confirmed Visitor Arrived'), ('MEETING_START', 'Meeting Started'), ('MEETING_END', 'Meeting Completed'), ('NO_SHOW', 'Visitor Did Not Show'), ('DENIED', 'Host Denied Visit')], max_length=20)),
                ('confirmed_by', models.CharField(help_text='Name/ID of person confirming', max_length=100)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='visitors.visitor')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
