# Generated by Django 6.0.2 on 2026-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_enhance_visitor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='visitor_qr_codes/'),
        ),
    ]
