# Generated by Django 6.0.2 on 2026-02-20 05:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('camera', 'Camera'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the asset')),
                ('qr_code', models.CharField(blank=True, max_length=200, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/assets/')),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_reported_stolen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayScholarStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in', 'Checked In'), ('out', 'Checked Out')], default='out', max_length=10)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_scholar_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Scholar Status',
                'verbose_name_plural': 'Day Scholar Statuses',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('truck', 'Truck'), ('van', 'Van')], default='car', max_length=20)),
                ('make', models.CharField(help_text='e.g., Toyota, Honda', max_length=50)),
                ('model', models.CharField(help_text='e.g., Corolla, Civic', max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=200, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/vehicles/')),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_reported_stolen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('asset_verification', 'Asset Verification'), ('vehicle_entry', 'Vehicle Entry'), ('vehicle_exit', 'Vehicle Exit'), ('day_scholar_in', 'Day Scholar Check In'), ('day_scholar_out', 'Day Scholar Check Out'), ('visitor_entry', 'Visitor Entry'), ('visitor_exit', 'Visitor Exit'), ('security_alert', 'Security Alert')], max_length=30)),
                ('status', models.CharField(choices=[('valid', 'Valid/Authorized'), ('invalid', 'Invalid/Unauthorized'), ('visitor', 'Visitor'), ('stolen', 'Reported Stolen'), ('expired', 'Expired')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('location', models.CharField(blank=True, help_text='Gate location', max_length=100)),
                ('visitor_name', models.CharField(blank=True, help_text='Name of visitor (if applicable)', max_length=200)),
                ('visitor_id', models.CharField(blank=True, help_text='ID of visitor', max_length=100)),
                ('visitor_purpose', models.CharField(blank=True, help_text='Purpose of visit', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatemanager.asset')),
                ('guard', models.ForeignKey(help_text='Security guard who made the log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User involved in the log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatemanager.vehicle')),
            ],
            options={
                'verbose_name': 'Gate Log',
                'verbose_name_plural': 'Gate Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', 'asset_type'], name='gatemanager_user_id_576f91_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='gatemanager_serial__c23497_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['qr_code'], name='gatemanager_qr_code_661e93_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'plate_number'], name='gatemanager_user_id_c826c5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='gatemanager_plate_n_a862a3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['qr_code'], name='gatemanager_qr_code_aaa633_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['timestamp', 'log_type'], name='gatemanager_timesta_813307_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['user', 'timestamp'], name='gatemanager_user_id_dbcc95_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['guard', 'timestamp'], name='gatemanager_guard_i_f2a01b_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['status'], name='gatemanager_status_12bb64_idx'),
        ),
    ]
