# Generated by Django 6.0.2 on 2026-02-21 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
