# Generated by Django 6.0.2 on 2026-02-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('VEHICLE_ENTRY', 'Vehicle Entry'), ('VEHICLE_EXIT', 'Vehicle Exit'), ('ASSET_VERIFY', 'Asset Verification'), ('SCHOLAR_IN', 'Day Scholar Sign In'), ('SCHOLAR_OUT', 'Day Scholar Sign Out'), ('VISITOR_ENTRY', 'Visitor Entry')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('plate_number_raw', models.CharField(blank=True, max_length=20)),
                ('is_visitor', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
            ],
        ),
    ]
