# Generated by Django 6.0.2 on 2026-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_logs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatelog',
            name='declared_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='driver_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
